function Jfoot = RobotLegJfoot(in1)
%ROBOTLEGJFOOT
%    JFOOT = ROBOTLEGJFOOT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    01-Nov-2015 19:05:49

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = pi.*(1.0./2.0);
t7 = t6+th3;
t8 = t2.*t3.*(1.0./8.0);
t9 = cos(t7);
t10 = t2.*t3;
t17 = t4.*t5;
t11 = t10-t17;
t12 = t9.*t11.*(1.0./1.6e1);
t13 = sin(t7);
t14 = t2.*t5;
t15 = t3.*t4;
t16 = t14+t15;
t18 = t2.*t5.*(1.0./8.0);
t19 = t3.*t4.*(1.0./8.0);
t20 = t9.*t16.*(1.0./1.6e1);
t21 = t11.*t13.*(1.0./1.6e1);
Jfoot = reshape([t2.*(1.0./8.0)+t8+t12-t4.*t5.*(1.0./8.0)-t13.*t16.*(1.0./1.6e1),0.0,t4.*(1.0./8.0)+t18+t19+t20+t21,t8+t12-t4.*t5.*(1.0./8.0)-t13.*t16.*(1.0./1.6e1),0.0,t18+t19+t20+t21,t12-t13.*t16.*(1.0./1.6e1),0.0,t20+t21],[3,3]);
