function DrawBall(Ball)
surf(Ball.dims.radius*Ball.dims.x + Ball.states(1),...
    Ball.dims.radius*Ball.dims.y + Ball.states(2),...
    Ball.dims.radius*Ball.dims.z + Ball.states(3),...
    Ball.color.values);
%shading interp